### ISSUE TITLE
Crash when checking French

### ISSUE THREAD

**Issue by fungiboletus** [silvio/docker-languagetool#2]
Hi,

I'm trying your container (thanks by the way), and while it works with `en-GB`, it crashes with `fr`.

This is the error : `Native library (tmp/jna8006292366090954406.libhunspell-linux-x86-64.so) not found in resource path ([file:/LanguageTool-3.7/languagetool-server.jar])` 

Any idea ?

**Comment by silvio** [comment]
Thanks for your report. I have to look into this.

**Comment by danielnaber** [comment]
For some languages, LT needs (and usually provides itself) native libraries which it accesses via JNA. See https://github.com/languagetool-org/languagetool/blob/master/languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/Hunspell.java#L78 ... I'm not sure why it doesn't work in Docker without debugging. Is there no stacktrace?

**Comment by silvio** [comment]
I have understood the problem. Thanks @danielnaber to point to the provided libhunspell. The libhunspell is build with a gnu-libc. The dockerimage is using alpine and therefore it is using musl-libc.

Two possibilities:

* switch to `debian:jessie` images
* build languagetool via dockerfile

Depends on [#704](https://github.com/languagetool-org/languagetool/issues/704) what the way to go.

The fastest solution for now is to switch to `debian:jessie`.

**Comment by silvio** [comment]
The problem is fixed @yellowiscool. A `docker pull silviof/docker-languagetool` should give you a working image.

**Comment by fungiboletus** [comment]
Yes I confirm it works great. Thanks for the quick answers and the quick fix.
