### ISSUE TITLE
Clarify that routes exist on `/v2/`

### ISSUE THREAD

**Issue by KevinDanikowski** [silvio/docker-languagetool#25]
The error you receive when attempting to use any main route is:

> Error: This is the LanguageTool API. You have not specified any parameters. Please see https://languagetool.org/http-api/swagger-ui/#/default

Which took a little while until I learned all I was missing was `/v2` from the path. It would be helpful to add this to the README.

**Comment by silvio** [comment]
Hi @KevinDanikowski,
Can you give me some context, I do not understand what is meant. However, you could also very happily create a PullRequest. :-)

Thanks

**Comment by KevinDanikowski** [comment]
No problem: https://github.com/silvio/docker-languagetool/pull/28

**Comment by silvio** [comment]
Thanks @KevinDanikowski
