### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by AnimMouse** [silvio/docker-languagetool#41]
Without a license, I can't modify your code since technically the source code fall under your exclusive copyright.
Can you please add a license? I would suggest this license LGPLv3 or LGPLv2.1 so that it somewhat mirror the license of LanguageTool itself.

**Comment by silvio** [comment]
Hi @AnimMouse.

Hi!
I've been thinking for a long time about how to approach this topic. Unfortunately, I am not familiar with licences and their effects. I would follow your suggestion to use the LGPL, but first I would like to ask the community what suggestions they have.
Let's wait here another week, if nothing comes, I'll create a PR.

**Comment by FlyinPancake** [comment]
This doc might be of help
https://choosealicense.com/licenses/

**Comment by silvio** [comment]
@FlyinPancake Thanks for the hint. I created #58 for this now.

... still not sure about licences ;-)
