### ISSUE TITLE
[FR] Option to hide "Always Ignore" / "Ignore"

### ISSUE THREAD

**Issue by bonnebulle** [silvio/docker-languagetool#44]
If, like me you want win millisecondes, removing the two first lines ("Always Ignore" / "Ignore") is a good option... What do you think ?
Thanks, great works here !

**Comment by silvio** [comment]
I am not sure what you are referring to. If you already have a solution ready, we can discuss in a PR.

**Comment by bonnebulle** [comment]
Sorry, I am not asking in the right place... 
Am using this docker server-side w/ VScodium
( where I would like to change the UX "always ignore" )
Thanks for your time and good work
