### ISSUE TITLE
Installing ngrams

### ISSUE THREAD

**Issue by bonanza123** [silvio/docker-languagetool#5]
Sorry for the possibly stupid question, but how is it possible to download the ngrams?
Aren't they supposed to be downloaded from 
http://languagetool.org/download/ngram-data/
and extracted to
/usr/share/ngrams?

Would it then make sense to create a separate volume for this such that they are persistently stored?

**Comment by silvio** [comment]
Hi @bonanza123 , **n-grams** are absolutely new to me. After reading of [this page](http://wiki.languagetool.org/finding-errors-using-n-gram-data) I think I can prepare this image to handle the possibility of a additional mounted volume with n-gram data.

**Comment by bonanza123** [comment]
@silvio thanks so much!
