### ISSUE TITLE
Push latest 6.3a update to Dockerhub

### ISSUE THREAD

**Issue by thatso** [silvio/docker-languagetool#61]
Please push the latest [6.3a update](https://github.com/silvio/docker-languagetool/pull/60) to dockerhub as it still says ["Last pushed 2 months ago"](https://hub.docker.com/r/silviof/docker-languagetool/tags).

**Comment by silvio** [comment]
I forgot to push the tag. ^^
Sorry - this should not take so long time.

![image](https://github.com/silvio/docker-languagetool/assets/79472/d98eb7af-fea6-4e6e-9f18-b005af7809da)

The image is automatically build and pushed.
