### ISSUE TITLE
Docker build fails: Missing package openjdk-8-jre-headless

### ISSUE THREAD

**Issue by Erikvl87** [silvio/docker-languagetool#9]
The `openjdk-8-jre-headless` package [seems to be missing](https://packages.debian.org/search?keywords=openjdk&searchon=names&section=all&suite=jessie-backports) from the `jessie-backports` suite.

The Docker build will fail because of this:

```
+ apt-get -t jessie-backports install -y bash openjdk-8-jre-headless unzip
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package openjdk-8-jre-headless
```

I think this is also causing the following issue of pulling and running the `latest` tag from Docker Hub: `Error: Could not find or load main class org.languagetool.server.HTTPServer`.

Would you be able to tag individual versions in Docker Hub next to the `latest` tag so I can pin onto an older release when needed?

**Comment by Erikvl87** [comment]
Found someone else experiencing the same issues.
https://stackoverflow.com/questions/55298245/missing-openjdk-8-jre-headles-http-deb-debian-org-debian-jessie-backports-mai

**Comment by silvio** [comment]
Thanks for pointing me.
